#ifndef DX100_CTRL_H
#define DX100_CTRL_H

BOOL Dx100CtrlInit( HWND hWndEdit );

enum
{
    DX100_CTRL_MODE_SYSTEM     ,
    DX100_CTRL_MODE_PERFORMANCE,
    DX100_CTRL_MODE_PATCH      ,
    DX100_CTRL_MODE_GM         ,
    DX100_CTRL_MODE_NUM_MAX
};
typedef INT DX100_CTRL_MODE;

enum
{
    DX100_CTRL_PATCH_SUBMODE_COMMON,
    DX100_CTRL_PATCH_SUBMODE_TONE1 ,
    DX100_CTRL_PATCH_SUBMODE_TONE2 ,
    DX100_CTRL_PATCH_SUBMODE_TONE3 ,
    DX100_CTRL_PATCH_SUBMODE_TONE4 ,
    DX100_CTRL_PATCH_SUBMODE_NUM_MAX
};
typedef INT DX100_CTRL_PATCH_SUBMODE;

enum
{
    DX100_CTRL_PERFORMANCE_SUBMODE_COMMON,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART1 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART2 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART3 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART4 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART5 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART6 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART7 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART8 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART9 ,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART10,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART11,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART12,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART13,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART14,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART15,
    DX100_CTRL_PERFORMANCE_SUBMODE_PART16,
    DX100_CTRL_PERFORMANCE_SUBMODE_NUM_MAX
};
typedef INT DX100_CTRL_PERFORMANCE_SUBMODE;

BOOL Dx100CtrlModeSet(DX100_CTRL_MODE mode,DX100_CTRL_PATCH_SUBMODE patchSubMode,DX100_CTRL_PERFORMANCE_SUBMODE performanceSubMode);

BOOL Dx100CtrlDisplayUpdate( void );

enum
{
    DX100_CTRL_SEQ_METHOD_GET,
    DX100_CTRL_SEQ_METHOD_SET,
    DX100_CTRL_SEQ_MEDHOD_NUM__MAX
};
typedef INT DX100_CTRL_SEQ_METHOD;

enum
{
    DX100_CTRL_SEQ_NON_EXEC    ,
    DX100_CTRL_SEQ_SYS_COMMON  ,
    DX100_CTRL_SEQ_PATCH_COMMON,
    DX100_CTRL_SEQ_PATCH_TONE1 ,
    DX100_CTRL_SEQ_PATCH_TONE2 ,
    DX100_CTRL_SEQ_PATCH_TONE3 ,
    DX100_CTRL_SEQ_PATCH_TONE4 ,
    DX100_CTRL_SEQ_NUM_MAX
};
typedef INT DX100_CTRL_SEQ_ID;

BOOL Dx100CtrlSeqStart( DX100_CTRL_SEQ_METHOD method, DX100_CTRL_SEQ_ID seqIdStart, DX100_CTRL_SEQ_ID seqIdEnd );
BOOL Dx100CtrlDisplayContents( void );
void Dx100CtrlCycleProc( void );

#endif /* DX100_CTRL_H */
